name: continuous-integration-foo

on:
  push: #pull-request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle!
      working-directory: .  #//but for project: ./src/Platform
      run: ./gradlew build -x test
    - name: Run tests
      working-directory: .
      run: ./gradlew build